---
- name: "Play 1: Create new user"
  connection: network_cli
  gather_facts: false
  hosts: "csr-routers"
  tasks: 

    - name: "Tasks 1: create user and password"
      ios_user: 
        name: ansible
        configured_password: ansible
        privilege: 15
        state: present
    
    - name: "Task 2: show configured users"
      ios_command:
        commands:
           - show run | i user
      register: cli_output

    - name: "Task 3: copy to file"
      copy: contents="{{ cli_output }}" dest=./output/{{ inventory_hostname }}.txt
...
